services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: 260203
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "Effective_Mobile"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init_up.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d Effective_Mobile" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  site:
    image: yurademenev/effective_mobile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8080:8080
    volumes:
      - ./config:/config
